--Assignment
--95PAGE
SELECT * FROM EMPLOYEES

--SHOW DISTINCT JOB_ID 
SELECT DISTINCT(JOB_ID) FROM EMPLOYEES

--ALIAS
SELECT EMPLOYEE_ID AS 'EMP#', LAST_NAME 'EMPLOYEE', JOB_ID 'JOB', HIRE_DATE 'HIRE DATE' FROM EMPLOYEES

--JOIN LAST_NAME AND JOB_ID COLUMN
SELECT LAST_NAME + ', ' + JOB_ID AS 'EMPLOYEE AND TITLE' FROM EMPLOYEES

SELECT CONVERT(VARCHAR, EMPLOYEE_ID) + ', ' + FIRST_NAME + ', ' + LAST_NAME + ', ' + EMAIL + ', ' + PHONE_NUMBER + ', ' + CONVERT(VARCHAR, HIRE_DATE) + ', ' + JOB_ID + ', ' + CONVERT(VARCHAR, SALARY) +  ', ' + CONVERT(VARCHAR, DEPARTMENT_ID) AS THE_OUTPUT FROM EMPLOYEES

--126PAGE
SELECT LAST_NAME, SALARY FROM EMPLOYEES WHERE SALARY > 12000

SELECT LAST_NAME, DEPARTMENT_ID FROM EMPLOYEES WHERE EMPLOYEE_ID=176

SELECT LAST_NAME, SALARY FROM EMPLOYEES WHERE SALARY NOT BETWEEN 5000 AND 12000

--127
SELECT LAST_NAME, JOB_ID, HIRE_DATE FROM EMPLOYEES WHERE HIRE_DATE BETWEEN '17-JUNE-2003' AND '21-SEP-2005'

SELECT LAST_NAME, DEPARTMENT_ID FROM EMPLOYEES WHERE DEPARTMENT_ID IN(20, 50) ORDER BY LAST_NAME

SELECT * FROM EMPLOYEES

SELECT LAST_NAME AS 'EMPLOYEE', SALARY AS 'MONTHLY SALARY' FROM EMPLOYEES WHERE (SALARY BETWEEN 5000 AND 12000) AND (DEPARTMENT_ID=20 OR DEPARTMENT_ID=50)

--128PAGE
SELECT LAST_NAME, HIRE_DATE FROM EMPLOYEES WHERE HIRE_DATE='19-MARCH-2005'

SELECT LAST_NAME, JOB_ID FROM EMPLOYEES WHERE MANAGER_ID IS NULL

SELECT LAST_NAME, SALARY, COMMISSION_PCT FROM EMPLOYEES ORDER BY SALARY DESC, COMMISSION_PCT DESC

SELECT LAST_NAME FROM EMPLOYEES WHERE LAST_NAME LIKE '__A%'

SELECT LAST_NAME FROM EMPLOYEES WHERE LAST_NAME LIKE '%A%' OR LAST_NAME LIKE '%E%'

--129
SELECT * FROM EMPLOYEES
SELECT * FROM JOBS
SELECT LAST_NAME, JOB_ID, SALARY FROM EMPLOYEES WHERE JOB_ID IN(SELECT JOB_ID FROM JOBS WHERE JOB_TITLE IN('SALES REPRESENTATIVE','STOCK CLERK')) AND (SALARY NOT IN(2500, 3500, 7000))

SELECT LAST_NAME, SALARY, COMMISSION_PCT FROM EMPLOYEES WHERE COMMISSION_PCT= 0.2

--189
SELECT GETDATE() AS 'DATE'

SELECT EMPLOYEE_ID, LAST_NAME, SALARY, FLOOR(SALARY+(SALARY*(0.15))) AS 'NEW SALARY', FLOOR(((SALARY+(SALARY*(0.15))) - SALARY)) AS 'INCREASE' FROM EMPLOYEES

--191
SELECT LAST_NAME, DATEDIFF(M, HIRE_DATE, GETDATE()) AS 'MONTHS_WORKED' FROM EMPLOYEES 

SELECT LAST_NAME + ' EARNS $' + CONVERT(VARCHAR, SALARY) + ' MONTHLY BUT WANTS $' + CONVERT(VARCHAR, SALARY*3)  AS 'DREAM SALARIES' FROM EMPLOYEES

--234
SELECT LAST_NAME, E.DEPARTMENT_ID, DEPARTMENT_NAME FROM EMPLOYEES E JOIN DEPARTMENTS D ON E.DEPARTMENT_ID=D.DEPARTMENT_ID

SELECT * FROM JOBS
SELECT * FROM LOCATIONS
SELECT *  FROM EMPLOYEES
SELECT * FROM DEPARTMENTS
SELECT DISTINCT(JOB_ID), L.LOCATION_ID FROM EMPLOYEES E JOIN DEPARTMENTS D ON E.DEPARTMENT_ID=D.DEPARTMENT_ID JOIN LOCATIONS L ON D.LOCATION_ID=L.LOCATION_ID WHERE D.DEPARTMENT_ID=30 OR L.LOCATION_ID=90

SELECT LAST_NAME, DEPARTMENT_NAME, D.LOCATION_ID, CITY FROM EMPLOYEES E JOIN DEPARTMENTS D ON E.DEPARTMENT_ID=D.DEPARTMENT_ID JOIN LOCATIONS L ON D.LOCATION_ID=L.LOCATION_ID WHERE COMMISSION_PCT IS NOT NULL

SELECT LAST_NAME, JOB_ID, D.DEPARTMENT_ID, DEPARTMENT_NAME FROM EMPLOYEES E JOIN DEPARTMENTS D ON E.DEPARTMENT_ID=D.DEPARTMENT_ID WHERE LOCATION_ID IN(SELECT LOCATION_ID FROM LOCATIONS WHERE CITY = 'SEATTLE')

SELECT E.LAST_NAME 'EMPLOYEE', E.EMPLOYEE_ID 'EMP#', M.LAST_NAME 'MANAGER', M.MANAGER_ID 'Mgr#' FROM EMPLOYEES E JOIN EMPLOYEES M ON E.MANAGER_ID=M.EMPLOYEE_ID

SELECT E.DEPARTMENT_ID 'DEPARTMENT', E.LAST_NAME 'EMPLOYEE' FROM EMPLOYEES E JOIN EMPLOYEES E1 ON E.DEPARTMENT_ID = E1.DEPARTMENT_ID

SELECT * FROM job_grades;
SELECT * FROM EMPLOYEES

SELECT LAST_NAME, JOB_ID, DEPARTMENT_NAME, SALARY FROM EMPLOYEES E JOIN DEPARTMENTS D ON E.DEPARTMENT_ID=D.DEPARTMENT_ID 
SELECT GRADE 'GRA' FROM job_grades 

SELECT LAST_NAME, HIRE_DATE FROM EMPLOYEES WHERE HIRE_DATE >ALL(SELECT HIRE_DATE FROM EMPLOYEES WHERE FIRST_NAME = 'JOHN')

SELECT E1.FIRST_NAME 'EMPLOYEE', E1.HIRE_DATE 'EMP_HIRED' FROM EMPLOYEES E1 WHERE HIRE_DATE < (SELECT HIRE_DATE FROM EMPLOYEES E2 WHERE E2.EMPLOYEE_ID=E1.MANAGER_ID)
--268

SELECT JOB_ID, FLOOR(MAX(SALARY)) 'MAXIMUM' , FLOOR(MIN(SALARY)) 'MINIMUM', FLOOR(SUM(SALARY)) 'SUM', FLOOR(AVG(SALARY)) 'AVERAGE' FROM EMPLOYEES GROUP BY JOB_ID

SELECT JOB_ID, COUNT(EMPLOYEE_ID) FROM EMPLOYEES GROUP BY JOB_ID

SELECT COUNT(DISTINCT(MANAGER_ID)) 'NUMBER OF MANAGERS' FROM EMPLOYEES 

SELECT SUM(HIGHEST_SAL) - SUM(LOWEST_SAL) 'DIFFERENCE'  FROM job_grades

SELECT MANAGER_ID, SALARY 'MIN(SALARY)' FROM EMPLOYEES WHERE MANAGER_ID IS NOT NULL AND SALARY > 6000 ORDER BY SALARY DESC

--290
SELECT LAST_NAME, HIRE_DATE FROM EMPLOYEES WHERE DEPARTMENT_ID = (SELECT DEPARTMENT_ID FROM EMPLOYEES WHERE LAST_NAME='ZLOTKEY') AND LAST_NAME != 'ZLOTKEY'

SELECT EMPLOYEE_ID, LAST_NAME, SALARY FROM EMPLOYEES WHERE SALARY > (SELECT AVG(SALARY) FROM EMPLOYEES) ORDER BY SALARY 

SELECT EMPLOYEE_ID, LAST_NAME FROM EMPLOYEES WHERE DEPARTMENT_ID IN(SELECT DEPARTMENT_ID FROM EMPLOYEES WHERE LAST_NAME LIKE '%U%')

SELECT LAST_NAME, DEPARTMENT_ID, JOB_ID FROM EMPLOYEES  WHERE DEPARTMENT_ID IN(SELECT DEPARTMENT_ID FROM DEPARTMENTS WHERE LOCATION_ID = 1700)

SELECT * FROM LOCATIONS
SELECT * FROM DEPARTMENTS
SELECT * FROM EMPLOYEES

SELECT LAST_NAME, SALARY FROM EMPLOYEES E1 WHERE E1.MANAGER_ID IN(SELECT EMPLOYEE_ID FROM EMPLOYEES E2 WHERE E2.LAST_NAME = 'KING') 

SELECT DEPARTMENT_ID, LAST_NAME, JOB_ID FROM EMPLOYEES WHERE DEPARTMENT_ID = (SELECT DEPARTMENT_ID FROM DEPARTMENTS WHERE DEPARTMENT_NAME = 'IT')

SELECT EMPLOYEE_ID, LAST_NAME, SALARY FROM EMPLOYEES WHERE SALARY > (SELECT AVG(SALARY) FROM EMPLOYEES) AND DEPARTMENT_ID IN(SELECT DEPARTMENT_ID FROM EMPLOYEES WHERE LAST_NAME LIKE '%U%')










