//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_Pharmacy_System_Project.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Medicine
    {
        [Required(ErrorMessage="Please Enter Manager Id")]
        public int Medicine_Id { get; set; }

        [Required(ErrorMessage = "Please Enter Reference Number")]
        public Nullable<int> Reference_No { get; set; }

        [Required(ErrorMessage = "Please Enter Medicine Type")]
        public string Medicine_Type { get; set; }

        [Required(ErrorMessage = "Medicine Name Required For Placed Order")]
        public string Medicine_Name { get; set; }

        [Required(ErrorMessage = "Please Enter Mfg Date")]
        public Nullable<System.DateTime> Mfg_Date { get; set; }

        [Required(ErrorMessage = "Please Enter Exp Date")]
        public Nullable<System.DateTime> Exp_Date { get; set; }

        [Required(ErrorMessage = "Please Enter Medicine Price")]
        public Nullable<decimal> Medicine_Price { get; set; }
    }
}
