//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_Pharmacy_System_Project.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Pharmacist
    {
        [Required(ErrorMessage="Please Enter Id")]
        public int Pharmacist_Id { get; set; }

        [Required(ErrorMessage = "Please Enter First Name")]
        public string First_Name { get; set; }

        [Required(ErrorMessage = "Please Enter Last Name")]
        public string Last_Name { get; set; }

        [Required(ErrorMessage = "Please Enter Email")]
        public string Email { get; set; }

        [Required(ErrorMessage = "Please Enter Mobile Number")]
        public string Mobile_Number { get; set; }

        [Required(ErrorMessage = "Company Name Cannot Be Left Blank")]
        public string Company_Name { get; set; }

        [Required(ErrorMessage = "Please Enter Address")]
        public string Address { get; set; }
    }
}
