<?xml version="1.0" encoding="utf-8"?><Database Name="HRMSDB" Class="DeptLinqDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=LAPTOP-81HIQF3R\SQLEXPRESS;Initial Catalog=HRMSDB;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="HRMSDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.DEPARTMENTS" Member="DEPARTMENTs">
    <Type Name="DEPARTMENT">
      <Column Name="DEPARTMENT_ID" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DEPARTMENT_NAME" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="MANAGER_ID" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="LOCATION_ID" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
    </Type>
  </Table>
</Database>