CREATE TABLE STUDENT
(
    STUDENT_ID INT NOT NULL PRIMARY KEY,
    FIRST_NAME VARCHAR(20),
	LAST_NAME VARCHAR(20),
	ADDRESS VARCHAR(50)

)

INSERT INTO STUDENT VALUES(2, 'Dev', 'Sharma', 'Ideal Paradise, Nashik')
INSERT INTO STUDENT VALUES(3, 'Minal', 'Datta', 'Yash Home, Pune')

SELECT * FROM STUDENT